name = "Krang"
uuid = "54806c32-d51a-438d-8447-e0041be2fbfb"
authors = ["Dominic <dchang3419@hotmail.com> and contributors"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
JacobiElliptic = "2a8b799e-c098-4961-872a-356c768d184c"
PolarizedTypes = "d3c5d4cd-a8ee-40d6-aac7-e34df5a20044"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
DocStringExtensions = "0.9"
JacobiElliptic = "0.1, 0.2"
GeometryBasics = "0.4"
PolarizedTypes = "0.1"
StaticArrays = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
