name = "Krang"
uuid = "54806c32-d51a-438d-8447-e0041be2fbfb"
authors = ["Dominic <dchang3419@hotmail.com> and contributors"]
version = "0.2.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
JacobiElliptic = "2a8b799e-c098-4961-872a-356c768d184c"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
PolarizedTypes = "d3c5d4cd-a8ee-40d6-aac7-e34df5a20044"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
DocStringExtensions = "0.9"
GeometryBasics = "0.4"
JacobiElliptic = "0.1, 0.2"
PolarizedTypes = "0.1"
Rotations = "1"
StaticArrays = "1"
julia = "1.10"
KernelAbstractions = "0.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
