name = "Kang"
uuid = "54806c32-d51a-438d-8447-e0041be2fbfb"
authors = ["Dominic <dchang3419@hotmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
JacobiElliptic = "2a8b799e-c098-4961-872a-356c768d184c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
StaticArrays = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
